spring:
  profiles:
    active: local
server:
  port: 8081

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: cbb-game-events
    consumer:
      group-id: backend-listener-group
      max-poll-records: 20
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2"
      properties:
        "spring.deserializer.value.delegate.class": "com.flutter.streaming.kafka.serializer.protobuf.ProtobufDeserializer"
        "protobuf.use.type.headers": true
